### ISSUE TITLE
08/26 科學營 1st.Workshop

### ISSUE THREAD

**Issue by bofish** [ntust-cdvc/Arduino-BT-remote-car#1]
- 主題：藍牙遙控小車實作
- 人數：<5人
- 時間：9:00～17:00
- 地點：術德或長興
- 內容：利用mBlock寫出Arduino程式控制藍牙驅動小車，請自備筆電為佳。

**Comment by bofish** [comment]
Post format: https://github.com/f2etw/jobs

**Comment by woodrow-shen** [comment]
The event is out of date, so this is closed.
